# These settings must match:
# - Port numbers specified in the ABB robot controller's system configurations for EGM communication.
egm:
  channel_1:
    port_number: 6511
    mech_unit_group: "rob1"
  channel_2:
    port_number: 6512
    mech_unit_group: "rob2"

# These settings must match:
# - Joint names extracted from the ABB robot controller.
#
# Please see http://wiki.ros.org/joint_limits_interface for more details about joint limits.
joint_limits:
  rob1_joint_1:
    has_velocity_limits: true
    max_velocity: 2.0
  rob1_joint_2:
    has_velocity_limits: true
    max_velocity: 2.0
  rob1_joint_3:
    has_velocity_limits: true
    max_velocity: 2.0
  rob1_joint_4:
    has_velocity_limits: true
    max_velocity: 2.0
  rob1_joint_5:
    has_velocity_limits: true
    max_velocity: 2.0
  rob1_joint_6:
    has_velocity_limits: true
    max_velocity: 2.0

  rob2_joint_1:
    has_velocity_limits: true
    max_velocity: 2.0
  rob2_joint_2:
    has_velocity_limits: true
    max_velocity: 2.0
  rob2_joint_3:
    has_velocity_limits: true
    max_velocity: 2.0
  rob2_joint_4:
    has_velocity_limits: true
    max_velocity: 2.0
  rob2_joint_5:
    has_velocity_limits: true
    max_velocity: 2.0
  rob2_joint_6:
    has_velocity_limits: true
    max_velocity: 2.0
